2022-03-22 15:15:24,048 INFO    MainThread:11415 [wandb_setup.py:_flush():75] Loading settings from /home/atharva1511/.config/wandb/settings
2022-03-22 15:15:24,048 INFO    MainThread:11415 [wandb_setup.py:_flush():75] Loading settings from /home/atharva1511/Downloads/CS6910/assignment2/code2/wandb/settings
2022-03-22 15:15:24,048 INFO    MainThread:11415 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-22 15:15:24,048 INFO    MainThread:11415 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'Downloads/CS6910/assignment2/code2/train.py', 'program': 'train.py'}
2022-03-22 15:15:24,048 INFO    MainThread:11415 [wandb_init.py:_log_setup():405] Logging user logs to /home/atharva1511/Downloads/CS6910/assignment2/code2/wandb/run-20220322_151524-21od1lnr/logs/debug.log
2022-03-22 15:15:24,048 INFO    MainThread:11415 [wandb_init.py:_log_setup():406] Logging internal logs to /home/atharva1511/Downloads/CS6910/assignment2/code2/wandb/run-20220322_151524-21od1lnr/logs/debug-internal.log
2022-03-22 15:15:24,048 INFO    MainThread:11415 [wandb_init.py:init():439] calling init triggers
2022-03-22 15:15:24,048 INFO    MainThread:11415 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {'checkpoint_dir': 'models', 'train_file_path': '../20/dataset1.csv', 'val_file_path': '../20/dataset1.csv', 'cuda': False, 'wandb': False, 'do_train': True, 'do_val': True, 'do_predict': True, 'use_trained': True, 'log_step': 100, 'batch_size': 1, 'epochs': 100, 'val_batch_size': 1, 'output_num': 5, 'input_num': 48, 'num_ae_hidden1': 35, 'num_ae_hidden2': 20, 'num_ae_output': 10, 'num_hidden1': 13, 'num_hidden2': 18, 'learning_rate': 0.001, 'momentum': 0.9198}
2022-03-22 15:15:24,048 INFO    MainThread:11415 [wandb_init.py:init():492] starting backend
2022-03-22 15:15:24,048 INFO    MainThread:11415 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-22 15:15:24,053 INFO    MainThread:11415 [backend.py:ensure_launched():219] starting backend process...
2022-03-22 15:15:24,059 INFO    MainThread:11415 [backend.py:ensure_launched():224] started backend process with pid: 11438
2022-03-22 15:15:24,060 INFO    MainThread:11415 [wandb_init.py:init():501] backend started and connected
2022-03-22 15:15:24,063 INFO    MainThread:11415 [wandb_init.py:init():565] updated telemetry
2022-03-22 15:15:24,066 INFO    MainThread:11415 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-22 15:15:25,070 INFO    MainThread:11415 [wandb_run.py:_on_init():1759] communicating current version
2022-03-22 15:15:25,119 INFO    MainThread:11415 [wandb_run.py:_on_init():1763] got version response 
2022-03-22 15:15:25,119 INFO    MainThread:11415 [wandb_init.py:init():625] starting run threads in backend
2022-03-22 15:15:26,409 INFO    MainThread:11415 [wandb_run.py:_console_start():1733] atexit reg
2022-03-22 15:15:26,410 INFO    MainThread:11415 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-03-22 15:15:26,410 INFO    MainThread:11415 [wandb_run.py:_redirect():1611] Redirecting console.
2022-03-22 15:15:26,412 INFO    MainThread:11415 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-22 15:15:26,412 INFO    MainThread:11415 [wandb_init.py:init():664] run started, returning control to user process
2022-03-22 15:17:48,638 INFO    MainThread:11415 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-22 15:17:48,638 INFO    MainThread:11415 [wandb_run.py:_restore():1674] restore
2022-03-22 15:17:56,594 INFO    MainThread:11415 [wandb_run.py:_on_finish():1831] got exit ret: None
2022-03-22 15:18:01,695 INFO    MainThread:11415 [wandb_run.py:_on_finish():1831] got exit ret: None
2022-03-22 15:18:06,797 INFO    MainThread:11415 [wandb_run.py:_on_finish():1831] got exit ret: None
2022-03-22 15:18:11,898 INFO    MainThread:11415 [wandb_run.py:_on_finish():1831] got exit ret: None
2022-03-22 15:18:16,999 INFO    MainThread:11415 [wandb_run.py:_on_finish():1831] got exit ret: None
