/home/atharva1511/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py:529: UserWarning: Using a target size (torch.Size([1, 48])) that is different to the input size (torch.Size([48])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Epoch - 0	 step - 12669 	Train loss - 25289931.855290547 	 MAE - 2869.7788873886752
Val loss: 22739634.588119082	 Val error: 135651.23414669864
Traceback (most recent call last):
  File "train.py", line 178, in <module>
    train_one_epoch1(model, trainloader, optimizer,
  File "train.py", line 50, in train_one_epoch1
    optimizer.step()
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/optim/optimizer.py", line 87, in wrapper
    with torch.autograd.profiler.record_function(profile_name):
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/autograd/profiler.py", line 433, in __init__
    self.handle: torch.Tensor = torch.zeros(1)
KeyboardInterrupt
Traceback (most recent call last):
  File "train.py", line 178, in <module>
    train_one_epoch1(model, trainloader, optimizer,
  File "train.py", line 50, in train_one_epoch1
    optimizer.step()
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/optim/optimizer.py", line 87, in wrapper
    with torch.autograd.profiler.record_function(profile_name):
  File "/home/atharva1511/.local/lib/python3.8/site-packages/torch/autograd/profiler.py", line 433, in __init__
    self.handle: torch.Tensor = torch.zeros(1)
KeyboardInterrupt